core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('', views.home, name='home'),
    path('mentions_legales/', views.legal_notice, name='legal_notice'),
]

favorites/urls.py
from django.urls import path
from . import views

app_name = "favorites"

urlpatterns = [
    path('favorites/', views.favorites, name='favorites'),
]

products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path('product/', views.product_details, name='product'),
]

purbeurre/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('search.urls')),
    path('', include('users.urls')),
    path('', include('products.urls')),
    path('', include('favorites.urls'))
]

search/urls.py
from django.urls import path
from . import views

app_name = "search"

urlpatterns = [
    path('resultats/', views.search_results, name='search_results'),
]

search/forms.py
from django import forms


class FavoritesForm(forms.Form):
    product = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Quel produit substituer ?'}),)

search/views.py
from django.shortcuts import render
from products.models import Product
import random


def search_results(request):
    surrogate_search = False
    surrogates = False
    surrogates_clean = []
    try:
        if request.GET:
            product_searched = request.GET.get("product_searched")
            first_result = Product.objects.filter(product_name__icontains=product_searched)[0]
            surrogate_search = True
        else:
            first_result = None
    except IndexError:
        first_result = False

    if surrogate_search:

        surrogates_raw = Product.objects.filter(
            category=first_result.category,
            nutrition_grade_fr__lt=first_result.nutrition_grade_fr
        )
        if surrogates_raw:
            for product in surrogates_raw:
                surrogates_clean.append(product)

            random.shuffle(surrogates_clean)
            surrogates = surrogates_clean[:6]

    return render(request, 'search/resultats.html', {
        'title': "Page de resultats",
        'product_found': first_result,
        'surrogates': surrogates,
    })

search/templates/search/resultats.html
{% extends "core/base.html" %}
{% load static %}
{% block content %}
<!-- Masthead -->

      {% if product_found == None %}
  <header class="results">
    <div class="container h-100">
        <h1 class="text-center text-white font-weight-bold">Oops !</h1>
      {% elif product_found == False %}
  <header class="results">
    <div class="container h-100">
        <h1 class="text-center text-white font-weight-bold">Oops !</h1>
      {% else %}
  <header class="results"
          style="
          background : linear-gradient(to bottom,rgba(92,77,66,.9) 0,rgba(92,77,66,.2) 100%),url({{product_found.image_url}});
          background-repeat : no-repeat;
          text-align : center;
          background-position: center;">
    <div class="container h-100">
      <h1><a class="text-center text-white font-weight-bold" href="{% url 'products:product' %}?code={{ product_found.code }}">{{ product_found.product_name }}</a></h1>
      {% endif %}
    </div>
  </header>

<!-- list of results -->
  <section class="results-section">
    {% if product_found == None %}
    <p class="text-center">Vous pouvez utiliser le champ dans la barre de navigation pour faire une recherche</p>
    {% elif product_found == False %}
    <p class="text-center">Nous n'avons trouvé aucun produit correspondant à votre recherche. Merci d'en essayer une autre</p>
    {% elif surrogates is False %}
    <h5 class="text-center mt-0">Ce produit à un nutriscore A</h5>
    <hr class="divider my-4">
    {% elif surrogates %}
    <div class="container">
      <h5 class="text-center mt-0">Vous pouvez remplacer cet aliment par :</h5>
      <hr class="divider my-4">

    <div class="row">
        {% for product in surrogates %}
        <div class="col-md-4 col-xs-12 col-lg-4-product" >
          <div class="col-lg-4-img" >
            {% if product.nutrition_grade_fr == 'a' %}
            <span class="nutriscore-a">A</span>
            {% elif product.nutrition_grade_fr == 'b' %}
            <span class="nutriscore-b">B</span>
            {% elif product.nutrition_grade_fr == 'c' %}
            <span class="nutriscore-c">C</span>
            {% elif product.nutrition_grade_fr == 'd' %}
            <span class="nutriscore-d">D</span>
            {% elif product.nutrition_grade_fr == 'e' %}
            <span class="nutriscore-e">E</span>
            {% endif %}
            <a class="fill-div" href="{% url 'products:product' %}?code={{ product.code }}">
              <img class ="imgproduct" src="{{ product.image_url }} " alt="{{ product.product_name }}">
              </a>
          </div>
          <a href="{% url 'products:product' %}?code={{ product.code }}"><h5 class="mb-3 text-center font-weight-bold">{{ product.product_name }}</h5></a>
            {% if user.is_authenticated %}
              <form class="text-center mb-3" action="{% url 'favorites:favorites' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="product" value="{{ product_found.code }}">
                <input type="hidden" name="substitute" value="{{ product.code }}">
                <button class="a-saveproduct" type="submit"><i class="fa fa-floppy-o" aria-hidden="true">&#xf0c7 </i>
                  Sauvegarder
                </button>
              </form>
            {% endif %}
        </div>
        {% endfor %}
      </div>
      </div>
    </div>
    {% else %}
    <p class="text-center">Une erreur c'est produite, merci de <a href="{% url 'core:home' %}#contact">nous contacter !</a></p>
    {% endif %}
  </section>

{% endblock content %}