core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('', views.home, name='home'),
    path('mentions_legales/', views.legal_notice, name='legal_notice'),
]

favorites/urls.py
from django.urls import path
from . import views

app_name = "favorites"

urlpatterns = [
    path('favorites/', views.favorites, name='favorites'),
]

purbeurre/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('search.urls')),
    path('', include('users.urls')),
    path('', include('products.urls')),
    path('', include('favorites.urls'))
]

search/urls.py
from django.urls import path
from . import views

app_name = "search"

urlpatterns = [
    path('resultats/', views.search_results, name='search_results'),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.login, name='login'),
    path('accounts/profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),

]

core/forms.py
from django import forms


class SearchForm(forms.Form):
    product_searched = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Quel produit substituer ?'}),)

core/views.py
from django.shortcuts import render
from .forms import SearchForm


def home(request):
    search_form = SearchForm(request.GET)
    return render(request, 'core/pages/home.html', {'title': "Page d'accueil", 'search_form': search_form})


def legal_notice(request):
    return render(request, 'core/pages/mentions_legales.html', {
        'title': "Mentions légales",
        'header_title': "Mentions légales"})

core/templates/core/layouts/_footer.html
<!-- Footer -->
  <footer class="bg-light py-5">
  <div class="container">
    <div class="row">
        <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
          <a href="{% url 'core:legal_notice' %}">Mentions légales</a>
        </div>
        <div class="col-lg-4 mr-auto text-center">
          <a href="{% url 'core:home' %}#contact">Contact</a>
        </div>
      </div>
    </div>
  </footer>
  </footer>

core/templates/core/layouts/_head.html
{% load static %}
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">


  <link rel="apple-touch-icon" sizes="57x57" href="{% static 'img/favicon/apple-icon-57x57.png' %}">
  <link rel="apple-touch-icon" sizes="60x60" href="{% static 'img/favicon/apple-icon-60x60.png' %}">
  <link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/favicon/apple-icon-72x72.png' %}">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/favicon/apple-icon-76x76.png' %}">
  <link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/favicon/apple-icon-114x114.png' %}">
  <link rel="apple-touch-icon" sizes="120x120" href="{% static 'img/favicon/apple-icon-120x120.png' %}">
  <link rel="apple-touch-icon" sizes="144x144" href="{% static 'img/favicon/apple-icon-144x144.png' %}">
  <link rel="apple-touch-icon" sizes="152x152" href="{% static 'img/favicon/apple-icon-152x152.png' %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicon/apple-icon-180x180.png' %}">
  <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'img/favicon/android-icon-192x192.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicon/favicon-96x96.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon/favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'img/favicon/manifest.json' %}">
  <meta name="msapplication-TileColor" content="#ffffff' %}">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png' %}">
  <meta name="theme-color" content="#ffffff' %}">

  {% if title %}
      <title>Pur Beurre - {{ title }}</title>
  {% else %}
      <title>Pur Beurre</title>
  {% endif %}

  <!-- Font Awesome Icons -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

  <!-- Google Fonts -->
  <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css">

  <!-- Plugin CSS -->
  <link href="{% static 'vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

  <!-- Theme CSS - Includes Bootstrap -->
  <link href="{% static 'css/creative.min.css' %}" rel="stylesheet">

</head>

core/templates/core/layouts/_navigation.html
{% load static %}
{% url 'core:home' as home_url %}

<!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{% url 'core:home' %}"><!-- pagetop : #page-top --><img class="logoheader" src="{% static 'img/logo.png' %}" alt="Logo">Pur Beurre</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto my-2 my-lg-0">
          {% if request.get_full_path != home_url %}
          <li class="nav-item my-auto">
            <form class="" action="{% url 'search:search_results' %}" method="get">
              <input type="text" name="product_searched" placeholder="Quel produit substituer ?" id="id_product_searched" class="navbar-form">
            </form>
          </li>
          {% endif %}
          <li class="nav-item my-auto">
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'users:profile' %}"><i class="fa fa-user"></i></a>
            {% else %}
            <a class="nav-link" id="login" href="{% url 'users:login' %}"><i class="fa fa-user"></i></a>
            {% endif %}
          </li>
          <li class="nav-item my-auto">
            <a class="nav-link" href="{% url 'favorites:favorites' %}"><i class="fas fa-carrot"></i></a>
          </li>
          <li class="nav-item my-auto">
            {% if user.is_authenticated %}
            <a class="nav-link" style="color: #f4623a" href="{% url 'users:logout' %}"><i class="fa fa-sign-out-alt"></i></a>
            {% else %}
            <a class="nav-link" href="#"><i class="fa fa-sign-out-alt"></i></a>
            {% endif %}
          </li>
        </ul>
      </div>
    </div>
  </nav>

core/templates/core/layouts/_scripts.html
{% load static %}
<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Plugin JavaScript -->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
<script src="{% static 'vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

<!-- Custom scripts for this template -->
<script src="{% static 'js/creative.min.js' %}"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<script>
setTimeout(function() {
    $('#message_container').fadeOut(1600, "linear");
}, 5000); // <-- time in milliseconds
</script>